#!/bin/bash

BOOKSHELF=$(mktemp)

for i in $(seq 1 10000); do
    PAGE=$(mktemp)
    curl "https://booklog.jp/users/cympfh/all?category_id=all&status=all&sort=sort_desc&rank=all&tag=&page=${i}&keyword=&reviewed=&quoted=&json=true" > $PAGE
    if [ $(cat $PAGE | jq '.books | length') -eq 0 ]; then
        break
    fi
    cat $PAGE | jq -cM '.books[]' | nkf -Z >> $BOOKSHELF
    rm $PAGE
done

mv $BOOKSHELF /tmp/booklog.json
